name: Build and test

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16,18,20]
        os: [macos-12,macos-14,windows-latest,ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: script/ci/build-and-test.sh
        if: runner.os != 'Windows'
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          PACT_BROKER_FEATURES: publish_pacts_using_old_api
      - run: script/ci/build-and-test.sh
        if: runner.os == 'Windows'
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          # The windows build agent has trouble unpacking the tar for
          # linux, so we only download windows binaries. This means
          # we cannot release from Windows in CI.
          ONLY_DOWNLOAD_PACT_FOR_WINDOWS: true
          PACT_BROKER_FEATURES: publish_pacts_using_old_api